### ISSUE TITLE
Shield Not working

### ISSUE THREAD

**Issue by CoffeePuppy** [CoffeePuppy/Realm-of-Ethania-Issues#3]
**Describe the bug**
When blocking with shield the stamina goes down and only a percentage of the damage is blocked.

**To Reproduce**
Equip shield and get someone to attack you

**Expected behavior**
Shield takes damage and no damage goes to the player

**Screenshots**
no screenshots needed

**Additional context**
do it asap gleb smh

**Comment by retrofon** [comment]
wworking on it

**Comment by retrofon** [comment]
fixed
