### ISSUE TITLE
Reduction of Stamina Bar

### ISSUE THREAD

**Issue by Gepuwu** [CoffeePuppy/Realm-of-Ethania-Issues#4]
**Describe the bug**
The Stamina Bar is supposed to slowly go down to 0 but it just stops randomly and therefore lets you block infinitely 

**To Reproduce**
Step 1. Block
Step 2. Watch Stamina Bar go down (or don't witness it going down at all)
Step 3. Witness Stamina Bar not going down anymore 

**Expected behavior**
The Stamina Bar is supposed to go down to 0 without getting stuck at some point. Literally the point of it is to not let players block for infinite amount of time and this bug allows it.

**Comment by retrofon** [comment]
working!!

**Comment by retrofon** [comment]
fixed
